### ISSUE TITLE
ImportError: No module named serializers.json_coders

### ISSUE THREAD

**Issue by tlsong** [abinit/abipy#137]
hi,dear
when i test this example [http://pythonhosted.org/abipy/examples/plot/plot_bz.html](url)
It give me this message:
`ImportError                               Traceback (most recent call last)
<ipython-input-35-b932e92e7255> in <module>()
----> 1 from abipy.abilab import abiopen
      2 import abipy.data as abidata
      3 
      4 # Open the WKF file.
      5 wfk_file = abiopen(abidata.ref_file("si_scf_WFK.nc"))

/opt/anaconda2/lib/python2.7/site-packages/abipy/__init__.py in <module>()
     16 #-----------------------------------------------------------------------------
     17 
---> 18 from abipy.core import release
     19 #from abipy.profile import abipy_env
     20 #from abipy.htc import Launcher, MassLauncher, AbinitInput

/opt/anaconda2/lib/python2.7/site-packages/abipy/core/__init__.py in <module>()
      1 """Core objects."""
----> 2 from .kpoints import *
      3 from .structure import *
      4 from .symmetries import *
      5 from .gsphere import *

/opt/anaconda2/lib/python2.7/site-packages/abipy/core/kpoints.py in <module>()
     14 from monty.functools import lazy_property
     15 from pymatgen.core.lattice import Lattice
---> 16 from pymatgen.serializers.json_coders import pmg_serialize
     17 from pymatgen.serializers.pickle_coders import SlotPickleMixin
     18 from abipy.iotools import ETSF_Reader

ImportError: No module named serializers.json_coders`

The pymatgen is already installed, 
pip show pymatgen
`
Name: pymatgen
Version: 2017.12.16
Summary: Python Materials Genomics is a robust materials analysis code that defines core object representations for structures and molecules with support for many electronic structure codes. It is currently the core analysis code powering the Materials Project (https://www.materialsproject.org).
Home-page: http://www.pymatgen.org
Author: Shyue Ping Ong
Author-email: ongsp@eng.ucsd.edu
License: MIT
Location: /opt/anaconda2/lib/python2.7/site-packages
Requires: numpy, six, requests, ruamel.yaml, monty, scipy, pydispatcher, tabulate, spglib, matplotlib, palettable, sympy, pandas, enum34
`
could you tell me how to solve it. thank you very much!

**Comment by tlsong** [comment]
this could be solve by:
from pymatgen.serializers.json_coders import pmg_serialize
from pymatgen.util.serialization import pmg_serialize

from pymatgen.serializers.pickle_coders import SlotPickleMixin
from pymatgen.util.serialization import SlotPickleMixin

**Comment by gmatteo** [comment]
abipy v0.2 (the version available on PyPi) is not compatible with recent versions of pymatgen
because the pymatgen developers have renamed several public modules.

I'm preparing the release of abipy 0.3 that will fix these incompatibilities.

For the time being, one has to use the developmental version of abipy available on github
that is tested against the latest pymatgen.
Alternatively, one has to change the import statements as you did.

**Comment by setten** [comment]
is the version of pymatgen not fixed in the setup.py of the 0.2 version of
abipy?



Michiel van Setten
UCL, NAPS
mjvansetten@gmail.com
michiel.vansetten@uclouvain.be
010 478824
https://be.linkedin.com/in/michielvansetten

be.linkedin.com/in/michielvansetten
gw100.wordpress.com


2018-01-08 17:55 GMT+01:00 gmatteo <notifications@github.com>:

**Comment by gmatteo** [comment]
> is the version of pymatgen not fixed in the setup.py of the 0.2 version of
abipy?

No, but in v0.3, I will start to pin the pymatgen version

**Comment by gmatteo** [comment]
Abipy v0.3 is available on pip at <https://pypi.python.org/pypi/abipy/0.3.0>
and anaconda cloud <https://anaconda.org/abinit/abipy>
Requires: pymatgen==2018.2.13
