### ISSUE TITLE
Lobster cohp/coop/dos plotting import error

### ISSUE THREAD

**Issue by bradraj** [abinit/abipy#158]
I installed abipy 0.6.0 devel version. I tried the lobster notebook tutorial for plotting cohp. 

for this given command line in the jupyter notebook,

`from abipy.abilab import LobsterAnalyzer`

it is giving the below error:

ImportError: cannot import name 'LobsterAnalyzer'

**Comment by gmatteo** [comment]
This usually happens when jupyter is not installed in the same environment 
as the one used for AbiPy.

Could you give the output of

```shell
which jupyter
which python
```

On my Mac, for example, I use conda and I have:

```
which jupyter     # /Users/gmatteo/anaconda3/envs/env3.6/bin/jupyter
which python # /Users/gmatteo/anaconda3/envs/env3.6/bin/python
```

python setup.py install` installs AbiPy in 
 `/Users/gmatteo/anaconda3/envs/env3.6/lib/python3.6/site-packages/`
and jupyter will have access to the last version installed by setup.py

**Comment by bradraj** [comment]
It is working when the environment is same. Thanks a lot.

But the index of the different atom orbitals between Ga and As is blocking the p-COOP.
![coop](https://user-images.githubusercontent.com/5661414/42878004-28db94e4-8aa9-11e8-97c6-a6acbe679ca3.png)

**Comment by gmatteo** [comment]
Use the fontsize keyword argument to decrease the text size  fontsize e.g. 

```
fontsize=8
```

Note that this part of AbiPy is still under development and there's lot of room for improvement

**Comment by bradraj** [comment]
Thanks a lot for quick reply !
