### ISSUE TITLE
" abinp.py phonons " and ngkpt

### ISSUE THREAD

**Issue by lcodacal** [abinit/abipy#176]
Hi,
   I would like to test the phonon band structure convergence with ngkpt.
   I would like to know if there is a way to choose the grid. It looks like that abinp.py does not take into account the ngkpt value from the input file.
   Thank you for the code. It is really amazing !
   All the best,
                Luis

**Comment by gmatteo** [comment]
In 300166de787fe772991df632c2d0f351ce4322bf, I've added 3 new options 
to specify the smearing, the occupation scheme and the k-point sampling in terms 
of kppa i.e. the number of k-points per reciprocal atoms.

The script is just wrapping the factory functions we use to generate input files 
for high-throughput applications and these functions work with `kppa` instead of `ngkpt`.

For a more flexible API that allows you to build explicitly the input file, see 
[this notebook](https://nbviewer.jupyter.org/github/abinit/abitutorials/blob/master/abitutorials/dfpt/lesson_dfpt.ipynb)

**Comment by lcodacal** [comment]
Thank you very much !!!
   All the best,
                  Luis


Em seg, 11 de fev de 2019 às 20:23, gmatteo <notifications@github.com>
escreveu:
