### ISSUE TITLE
Problems with newer versions of pymatgen

### ISSUE THREAD

**Issue by TheIdealis** [abinit/abipy#223]
- abipy                     0.7.0                    pypi_0    pypi
- pymatgen             2022.0.8     py37h2527ec5_0    conda-forge

If I try to execute 

 > abiopen.py graphene_o_DS2_GSR.nc --expose -sns=talk

I get the following error:

 > AttributeError: module 'pymatgen' has no attribute 'Structure'

It can be fixed be replacing `pymatgen.Structure` with `pymatgen.core.Structure` in `abipy/core/structure.py` and `from pymatgen import SETTINGS` with `from pymatgen import SETTINGS` in `abipy/core/restapi.py`

**Comment by gmatteo** [comment]
Old versions of abipy (version <= 0.9) are not compatible with recent versions of pymatgen due to a refactoring of the imports that broke backward compatibility.

I suggest to update your version of abipy to 0.9 with

```
pip install abipy -U
```

Alternatively, you may want to install abipy from the conda-force channel. with:

```
conda install abipy -c conda-force
```

In this case, I would also suggest to install everything in a fresh enviroment.

**Comment by TheIdealis** [comment]
Thanks alot!
