### ISSUE TITLE
pytmatgen structure not abipy?

### ISSUE THREAD

**Issue by jzwanzig** [abinit/abipy#244]
https://github.com/abinit/abipy/blob/6299326fc1afe4ca5e2e3911a85c30aa64a8ccff/abipy/scripts/abistruct.py#L652

@gmatteo 

This line seems to fail because the structure in question does not have the abi_string attribute, it seems to be created as a pymatgen structure but without the abipy extensions that would include the abi_string attribute

**Comment by gmatteo** [comment]
Hi @jzwanzig,

>  it seems to be created as a pymatgen structure but without the abipy extensions that would include the abi_string attribute

Yes,  the [get_primitive](https://github.com/materialsproject/pymatgen/blob/30e36f658aa121ee58caf962e230014e0e3fbbf9/pymatgen/core/structure.py#L2027) method of pymatgen structure should use `self.__class__` when building a new object so that 
inheritance is preserved. There are however cases in which the method uses pymatgen.core.Structure to construct the primitive structure so we don't get an AbipyStructure.

Quick fix:

```diff
diff --git a/abipy/scripts/abistruct.py b/abipy/scripts/abistruct.py
index 4bdd6b08..1b75185f 100755
--- a/abipy/scripts/abistruct.py
+++ b/abipy/scripts/abistruct.py
@@ -646,6 +646,8 @@ def main():
     elif options.command == "primitive":
         structure = abilab.Structure.from_file(options.filepath)
         primitive = structure.get_primitive_structure(tolerance=0.25, use_site_props=False, constrain_latt=None)
+        # Cast to abipy structure because get_primitive may break inheritance.
+        primitive = abilab.Structure.as_structure(primitive)
         separator = "\n" + 90 * "="
         print("\nInitial structure:\n", structure, separator)
         print("\nPrimitive structure returned by pymatgen:\n", primitive, separator)
```
