### ISSUE TITLE
Shift fermi energy to zero

### ISSUE THREAD

**Issue by sheng12** [abinit/abipy#99]
I having problem in setting fermi energy to zero in my band structure plot. I followed the official abipy plot example plot_bands.py, with the figure having its fermi level as computed in Abinit. I notice that in the ebands module there is a function _fix_fermie(), which should use efermi as the energy zero.

How should I modify the code so the data is shifted to that of zero fermi energy?

**Comment by gmatteo** [comment]
For the time being, one has to change the value of the Fermi level manually with

`ebands.fermie = fermi_level_in_eV` 

where fermi_level_in_eV is the Fermi level computed at the end of the SCF run.
This problem will be fixed in the next version of Abinit (the netcdf files produced 
by NSCF calculations will contain the Fermi level computed in the previous GS run).

**Comment by gmatteo** [comment]
fixed in abipy v0.2, requires Abinit > 8.2.2 in which the Fermi level computed at the end of SCF run is passed to the NSCF run and saved in the the netcdf file.
